name: Remove action@github.com commits

on:
  workflow_dispatch:  # 手动触发

jobs:
  remove-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 必须拉取完整历史

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          curl -L https://github.com/newren/git-filter-repo/raw/main/git-filter-repo -o git-filter-repo
          chmod +x git-filter-repo
          sudo mv git-filter-repo /usr/local/bin/

      - name: Remove commits by action@github.com
        run: |
          git filter-repo --commit-callback '
              if commit.author_email == b"action@github.com":
                  commit.skip()
          '

      - name: Force push updated history
        run: |
          git push origin --force --all
          git push origin --force --tags
