name: Rewrite history drop action@github.com
on:
  workflow_dispatch: {}

# 让 GITHUB_TOKEN 也有写权限（备用）
permissions:
  contents: write

jobs:
  rewrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # 我们用 PAT，自带凭据关掉

      - name: Configure git user
        run: |
          git config user.name "history-rewriter"
          git config user.email "actions@users.noreply.github.com"

      - name: Install git-filter-repo
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3 curl
          curl -L https://github.com/newren/git-filter-repo/raw/main/git-filter-repo -o git-filter-repo
          chmod +x git-filter-repo
          sudo mv git-filter-repo /usr/local/bin/

      - name: Remove commits authored by action@github.com
        run: |
          git filter-repo --commit-callback '
            if commit.author_email == b"action@github.com":
              commit.skip()
          '

      - name: Recreate/point origin using PAT
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          if [ -z "$PAT" ]; then
            echo "::error::Missing PAT_TOKEN secret. Add a classic PAT with repo+workflow scopes."
            exit 1
          fi
          if git remote | grep -q '^origin$'; then
            git remote set-url origin https://$PAT@github.com/$REPO.git
          else
            git remote add origin https://$PAT@github.com/$REPO.git
          fi
          git remote -v

      - name: Force-push current branch, all branches and tags
        env:
          DEFAULT_BRANCH: ${{ github.ref_name }}
        run: |
          set -e
          BRANCH="${DEFAULT_BRANCH:-$(git symbolic-ref --short HEAD)}"
          echo "Pushing branch: $BRANCH"
          git push --force origin "$BRANCH"
          for ref in $(git for-each-ref --format="%(refname:short)" refs/heads/ | grep -v "^$BRANCH$"); do
            echo "Pushing branch: $ref"
            git push --force origin "$ref"
          done
          git push --force --tags

      - name: Sanity check (no remaining action@github.com)
        run: |
          git fetch --all --tags
          git log --all --pretty="%H %ae" | grep -c 'action@github.com' && exit 1 || echo "Clean ✅"
